services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile-api
    image: "nova-api-${DOCKER_TAG}"
    container_name: pettisco_api 
    ports:
      - 24300:5000
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: "novo-frontend-${DOCKER_TAG}"
    ports:
      - 15786:3000
